application:
    title: \${appDescription:MCH-Title}
    env: DEFAULT-\${user.name}
    version: \${jarVersion?:unknown}

logging:
    level:
        org:
            hibernate: ERROR
server:
    port: 8080
    error:
        include-message: always
spring:
    profiles:
        default: default
    datasource:
        url: jdbc:postgresql://\${mch.db-host}:5432/mch?stringtype=unspecified
        username: postgres
        password: postgres
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
cloud:
    aws:
        credentials:
            access-key: \${MCH_AWS_ACCESS_KEY}
            secret-key: \${MCH_AWS_ACCESS_SECRET}
        region:
            static: \${MCH_AWS_REGION}
        stack:
            auto: false
    bucket:
        name: mch-propertyphotos
management:
    server:
        port: 8181
    endpoint:
        health:
            show-values: always
    endpoints:
        web:
            base-path: /mch_asset_management-mgmt

# App properties
demo:
    app:
        jwt-cookie-name: demomch
        jwt-secret: demomch
        jwt-expiration: 86400000
        security-enable-csrf: false